#!/bin/bash

# aws cli
export PATH=/usr/local/bin:$PATH
AWS_CLI=$(which aws)
DEPLOYMENT_TASK_METADATA=$(curl -s ${ECS_CONTAINER_METADATA_URI}/task)
DEPLOYMENT_TASK_CLUSTER=$(echo "${DEPLOYMENT_TASK_METADATA}" |jq -r '.Cluster')
DEPLOYMENT_TASK_ARN=$(echo "${DEPLOYMENT_TASK_METADATA}" |jq -r '.TaskARN')
AWS_REGION=$(echo "${DEPLOYMENT_TASK_ARN}" |cut -d':' -f4)
DEPLOYMENT_TASK_ID=$(echo "${DEPLOYMENT_TASK_ARN}" |cut -d':' -f6 |cut -d'/' -f2)
DEPLOYMENT_TASK_URL="https://${AWS_REGION}.console.aws.amazon.com/ecs/home?region=${AWS_REGION}#/clusters/${DEPLOYMENT_TASK_CLUSTER}/tasks/${DEPLOYMENT_TASK_ID}"
DEPLOYMENT_TASK_LOGS_URL="https://${AWS_REGION}.console.aws.amazon.com/cloudwatch/home?region=${AWS_REGION}#logEventViewer:group=/ecs/ecs-deployment;stream=ecs/logs/${DEPLOYMENT_TASK_ID}"

# Test for missing ENV vars
if [[ -z $SQS_URL ]] ; then
    echo "SQS_URL is not set. You must specify Queue URL via ENV."
    exit 1
fi
if [[ -z $ECS_CLUSTER ]] ; then
    ECS_CLUSTER=default
fi
if [[ -z $ECS_TIMEOUT ]] ; then
    ECS_TIMEOUT=300
fi

# Define temp files
MSGFILE=newdef.msg
JSONFILE=newdef.json

# Enable Slack WebHook Notification if ENVs are set
SLACK_NOTIFY=false
if ! [[ -z $SLACK_WEBHOOK ]] ; then
    SLACK_NOTIFY=true
    if [[ -z $SLACK_CHANNEL ]] ; then SLACK_NOTIFY=false ; fi
    if [[ -z $SLACK_BOTNAME ]] ; then SLACK_BOTNAME="ecs-deployment" ; fi
    if [[ -z $SLACK_COLOR ]] ; then SLACK_COLOR="#335EFF" ; fi
fi

# Enable MS Teams Notification (via SNS) if ENVs are set
SNS_NOTIFY=false
if ! [[ -z $SNS_TOPIC ]] ; then
    SNS_NOTIFY=true
fi

# Failure function
failure () {
    ERROR_MGS="$1"
    LINK_URL="$2"
    echo "ERROR: ${ERROR_MGS}"
    echo "LINK_URL: ${LINK_URL}"
    if [[ $SLACK_NOTIFY == "true" ]] ; then 
        SLACK_PRETEXT="ECS Deployment Failure:"
        SLACK_MESSAGE="${ERROR_MGS}!"
        SLACK_COLOR="#FF0000"
        echo "Posting Slack Notification to WebHook: $SLACK_WEBHOOK";
        SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"pretext\":\":fire::fire:*${SLACK_PRETEXT} ${SLACK_MESSAGE}*:fire::fire:\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"Service\", \"value\":\"${SERVICE}\", \"short\":false}, {\"title\":\"Error Mesage\", \"value\":\"${ERROR_MGS}\", \"short\":false}]}] }"
        CURL_RESULT=$(curl -s -S -X POST --data-urlencode "$SLACK_PAYLOAD" $SLACK_WEBHOOK)
    fi
    if [[ $SNS_NOTIFY == "true" ]] ; then 
        SNS_SUBJECT="ECS Deployment Failure"
        SNS_MESSAGE="${SNS_SUBJECT}: ${ERROR_MGS}"
        SNS_SUMMARY="${SNS_MESSAGE}"
        SNS_ATTRIBUTES='{ 
            "color": { "DataType": "String", "StringValue": "ff0000" }, 
            "messagetype": { "DataType": "String", "StringValue": "pretext" }, 
            "summary": { "DataType": "String", "StringValue": "<SNS_SUMMARY>" }, 
            "order": {  "DataType": "String.Array", "StringValue": "[ \"facts\" ]" },
            "items": { "DataType": "String", "StringValue": "[ { \"name\": \"Service\", \"value\": \"<SERVICE>\" }, { \"name\": \"Error Message\", \"value\": \"<ERROR_MGS>\" } ]" },
            "buttons": { "DataType": "String", "StringValue": "[ { \"name\": \"View\", \"value\": \"<LINK_URL>\" } ]" } 
            }'
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<SNS_SUMMARY\>/${SNS_SUMMARY}}"
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<SERVICE\>/${SERVICE}}"
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<ERROR_MGS\>/${ERROR_MGS}}"
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<LINK_URL\>/${LINK_URL}}"
        SNS_SENT=$($AWS_CLI sns publish --topic-arn $SNS_TOPIC --subject "$SNS_SUBJECT" --message "$SNS_MESSAGE" --message-attributes "$SNS_ATTRIBUTES" )
    fi
    if [[ $RECEIPT == "null" ]] || [[ -z $RECEIPT ]] ; then
        return 0
    else
        echo "Removing SQS message: $RECEIPT";
        DEL_SQS_MSG=$($AWS_CLI sqs delete-message --queue-url $SQS_URL --receipt-handle $RECEIPT)
        return 0
    fi
}


# Fetch new message from SQS
echo "Fetching SQS Message from Queue: $SQS_URL";
$AWS_CLI sqs receive-message --queue-url $SQS_URL --message-attribute-names All --visibility-timeout 300 > $MSGFILE

# Check new message is not empty
if ! [[ -s $MSGFILE ]] ; then echo "SQS Queue was empty (or Receive Message failed)." && exit 1; fi


# Get message ID (test for valid sqs json)
MSGID=$(jq -r '.Messages[0]|.MessageId' < $MSGFILE )
if [[ $MSGID == "null" ]] || [[ -z $MSGID ]] ; then failure "SQS Message malformed (Msg ID not found)" "$DEPLOYMENT_TASK_URL" && exit 1; fi
echo "SQS Message ID: $MSGID";

# Get message receipt handle (for deletion)
RECEIPT=$(jq -r '.Messages[0]|.ReceiptHandle' < $MSGFILE )
if [[ $RECEIPT == "null" ]] || [[ -z $RECEIPT ]] ; then failure "SQS Message malformed (Receipt Handle not found)" "$DEPLOYMENT_TASK_URL" && exit 1; fi
echo "SQS Message Receipt Handle: $RECEIPT";

# Get service name from message attribute
SERVICE=$(jq -r '.Messages[0]|.MessageAttributes|.service|.StringValue' < $MSGFILE )
if [[ $SERVICE == "null" ]] || [[ -z $SERVICE ]] ; then failure "SQS Message malformed (Service attribute missing)" "$DEPLOYMENT_TASK_URL" && exit 1; fi

# Get commit url from message attribute (if included)
COMMIT_URL=$(jq -r '.Messages[0]|.MessageAttributes|.commit_url|.StringValue' < $MSGFILE )
if [[ $COMMIT_URL == "null" ]] || [[ -z $COMMIT_URL ]] ; then COMMIT_URL="false" && echo "Commit URL not included."; fi

# Extract task definition to json file
jq < $MSGFILE '.Messages[0]|.Body' |sed -e 's/"{/{/' |sed -e 's/}\\n"/}\\n/' |sed -e 's/}"/}/' | sed -e 's/\\\"/\"/g' | sed -e 's/\\"/"/g' |sed -e 's/\\n/\n/g' > $JSONFILE
if ! [[ -s $JSONFILE ]] ; then failure "Task Def JSON is empty" "$DEPLOYMENT_TASK_URL" && exit 1; fi
echo "New task definition for service: $SERVICE";


# Run some sanity checks on new task definition
NEW_TASK_FAMILY=$(jq -r '.family' < $JSONFILE )
if [[ $NEW_TASK_FAMILY == "null" ]] || [[ -z $NEW_TASK_FAMILY ]] ; then failure "Task Definition malformed (Family not found)" "$DEPLOYMENT_TASK_URL" && exit 1; fi
NEW_TASK_CONTAINERS=$(jq '.containerDefinitions' < $JSONFILE )
if [[ $NEW_TASK_CONTAINERS == "null" ]] || [[ -z $NEW_TASK_CONTAINERS ]] ; then failure "Task Definition malformed (Containers not found)" "$DEPLOYMENT_TASK_URL" && exit 1; fi
NEW_TASK_VOLUMES=$(jq '.volumes' < $JSONFILE )
if [[ $NEW_TASK_VOLUMES == "null" ]] || [[ -z $NEW_TASK_VOLUMES ]] ; then failure "Task Definition malformed (Volumes not found)" "$DEPLOYMENT_TASK_URL" && exit 1; fi


# Check service exists (if provided) and get current task definition name and task count
if ! [[ $SERVICE == "false" ]] ; then
    CURRENT_TASK_ARN=$($AWS_CLI ecs describe-services --services $SERVICE --cluster $ECS_CLUSTER | jq -r '.services[0].taskDefinition' )
    if [[ $CURRENT_TASK_ARN == "null" ]] || [[ -z $CURRENT_TASK_ARN ]] ; then failure "Service ${SERVICE} not found" "$DEPLOYMENT_TASK_URL" && exit 1; fi
    CURRENT_TASK=$(echo ${CURRENT_TASK_ARN} |cut -d':' -f6-7 |cut -d'/' -f2)
    echo "Current task definition: $CURRENT_TASK";
    
    DESIRED_TASK_COUNT=$($AWS_CLI ecs describe-services --services $SERVICE --cluster $ECS_CLUSTER | jq -r '.services[0].desiredCount' )
    if [[ $DESIRED_TASK_COUNT == "null" ]] || [[ -z $DESIRED_TASK_COUNT ]] ; then failure "Service ${SERVICE} TASK COUNT not found" "$DEPLOYMENT_TASK_URL" && exit 1; fi
    echo "Service task count: $DESIRED_TASK_COUNT";
fi


# Register the new task definition, and store its ARN
echo "Registering new task definition ...";
NEW_TASKDEF_ARN=$($AWS_CLI ecs register-task-definition --cli-input-json file://$JSONFILE | jq -r '.taskDefinition.taskDefinitionArn' )
if [[ $NEW_TASKDEF_ARN == "null" ]] || [[ -z $NEW_TASKDEF_ARN ]] ; then failure "Task definition registration failed for ${SERVICE}" "$DEPLOYMENT_TASK_URL" && exit 1; fi
NEW_TASKDEF=$(echo ${NEW_TASKDEF_ARN} |cut -d':' -f6-7 |cut -d'/' -f2)
NEW_TASKDEF_NAME=$(echo ${NEW_TASKDEF} |cut -d':' -f1)
NEW_TASKDEF_REV=$(echo ${NEW_TASKDEF} |cut -d':' -f2)
echo "New task definition registered: $NEW_TASKDEF";

# Remove SQS Message
echo "Removing SQS message: $RECEIPT";
DEL_SQS_MSG=$($AWS_CLI sqs delete-message --queue-url $SQS_URL --receipt-handle $RECEIPT)
RECEIPT=""

# Setup vars for Slack Notification
AWS_REGION=$(echo ${NEW_TASKDEF_ARN} |cut -d':' -f4)
SERVICE_URL="https://${AWS_REGION}.console.aws.amazon.com/ecs/home?region=${AWS_REGION}#/clusters/${ECS_CLUSTER}/services/${SERVICE}/tasks"
SERVICE_EVENTS_URL="https://${AWS_REGION}.console.aws.amazon.com/ecs/home?region=${AWS_REGION}#/clusters/${ECS_CLUSTER}/services/${SERVICE}/events"
TASKDEF_URL="https://${AWS_REGION}.console.aws.amazon.com/ecs/home?region=${AWS_REGION}#/taskDefinitions/${NEW_TASKDEF_NAME}/${NEW_TASKDEF_REV}"
SLACK_PRETEXT="ECS Deployment:"
SLACK_MESSAGE="Registered new Task Definition <${TASKDEF_URL}|${NEW_TASKDEF}>"
SNS_SUBJECT="ECS Deployment: ${NEW_TASKDEF_NAME}"
SNS_SUMMARY="${SNS_SUBJECT}"
SNS_MESSAGE="Registered new Task Definition [${NEW_TASKDEF}](${TASKDEF_URL})"

# Update the service (if specified)
if [[ $SERVICE == "false" ]] ; then
    echo "Service set to FALSE";
else 
    echo "Updating service: $SERVICE";
    UPDATE=$($AWS_CLI ecs update-service --cluster $ECS_CLUSTER --service $SERVICE --task-definition $NEW_TASKDEF_ARN)
    SLACK_MESSAGE="${SLACK_MESSAGE} \nStarting Service Update of <${SERVICE_URL}|${SERVICE}> with new Task Definition <${TASKDEF_URL}|${NEW_TASKDEF}>"
    SNS_MESSAGE="${SNS_MESSAGE} <br>Starting Service Update of [${SERVICE}](${SERVICE_URL}) with new Task Definition [${NEW_TASKDEF}](${TASKDEF_URL})"
fi

# Add Github Commit link if provided
if ! [[ $COMMIT_URL == "false" ]] ; then
    COMMIT_ID=$(echo ${COMMIT_URL} |sed 's/.*\/\(.*\)$/\1/')
    SLACK_MESSAGE="${SLACK_MESSAGE} \nCommit ID: <${COMMIT_URL}|${COMMIT_ID}>"
    SNS_MESSAGE="${SNS_MESSAGE} <br>Commit ID: [${COMMIT_ID}](${COMMIT_URL})"
fi

# Send Slack Notification (if enabled)
if [[ $SLACK_NOTIFY == "true" ]] ; then
    echo "Posting Slack Notification to WebHook: $SLACK_WEBHOOK";
    SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"${SLACK_PRETEXT}\", \"value\":\"${SLACK_MESSAGE}\", \"short\":false}]}] }"
    CURL_RESULT=$(curl -s -S -X POST --data-urlencode "$SLACK_PAYLOAD" $SLACK_WEBHOOK)
fi

# Send Teams SNS Notification (if enabled)
if [[ $SNS_NOTIFY == "true" ]] ; then 
    SNS_ATTRIBUTES='{ 
        "color": { "DataType": "String", "StringValue": "0000ff" }, 
        "messagetype": { "DataType": "String", "StringValue": "normal" }, 
        "summary": { "DataType": "String", "StringValue": "<SNS_SUMMARY>" }, 
        "order": {  "DataType": "String.Array", "StringValue": "[ \"message\" ]" }
        }'
    SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<SNS_SUMMARY\>/${SNS_SUMMARY}}"
    SNS_SENT=$($AWS_CLI sns publish --topic-arn $SNS_TOPIC --subject "$SNS_SUBJECT" --message "$SNS_MESSAGE" --message-attributes "$SNS_ATTRIBUTES" )
fi

# Exit now if no service update to wait for (or desired task count is zero)
if [[ $SERVICE == "false" ]] || [ $DESIRED_TASK_COUNT -lt 1 ] ; then
    echo "Success, new task definition registered.";
    exit 0
fi


# See if the service is able to come up again
echo "Waiting for service update to complete ...";
every=10
i=0
while [ $i -lt $ECS_TIMEOUT ] 
do
  # Scan the list of running tasks for that service, and see if one of them is the
  # new version of the task definition
  rm -f tasks
  
  $AWS_CLI ecs list-tasks --cluster $ECS_CLUSTER  --service-name $SERVICE --desired-status RUNNING \
    | jq '.taskArns[]' \
    | xargs -I{} $AWS_CLI ecs describe-tasks --cluster $ECS_CLUSTER --tasks {} >> tasks
  
  jq < tasks > results ".tasks[]| if .taskDefinitionArn == \"$NEW_TASKDEF_ARN\" then . else empty end|.lastStatus"
  
  RUNNING=$(grep -e "RUNNING" results)

  if ! [[ -z $RUNNING ]]; then
    echo "Service updated successfully, new task definition running.";
    SLACK_PRETEXT="ECS Service Update Successful:"
    SLACK_MESSAGE="Completed Service Update of <${SERVICE_URL}|${SERVICE}> with new Task Definition <${TASKDEF_URL}|${NEW_TASKDEF}>"
    SNS_SUBJECT="ECS Service Update Successful: ${SERVICE}"
    SNS_SUMMARY="${SNS_SUBJECT}"
    SNS_MESSAGE="Completed Service Update of [${SERVICE}](${SERVICE_URL}) with new Task Definition [${NEW_TASKDEF}](${TASKDEF_URL})"

	# Send Slack Notification (if enabled)
	if [[ $SLACK_NOTIFY == "true" ]] ; then
	    echo "Posting Slack Notification to WebHook: $SLACK_WEBHOOK";
	    SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"${SLACK_PRETEXT}\", \"value\":\"${SLACK_MESSAGE}\", \"short\":false}]}] }"
	    CURL_RESULT=$(curl -s -S -X POST --data-urlencode "$SLACK_PAYLOAD" $SLACK_WEBHOOK)
	fi

    # Send Teams SNS Notification (if enabled)
    if [[ $SNS_NOTIFY == "true" ]] ; then 
        SNS_ATTRIBUTES='{ 
            "color": { "DataType": "String", "StringValue": "00ff00" }, 
            "messagetype": { "DataType": "String", "StringValue": "normal" }, 
            "summary": { "DataType": "String", "StringValue": "<SNS_SUMMARY>" }, 
            "order": {  "DataType": "String.Array", "StringValue": "[ \"message\" ]" },
            "buttons": { "DataType": "String", "StringValue": "[ { \"name\": \"Service Events\", \"value\": \"<SERVICE_EVENTS_URL>\" }, { \"name\": \"Deployment Logs\", \"value\": \"<DEPLOYMENT_TASK_LOGS_URL>\" } ]" } 
            }'
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<SNS_SUMMARY\>/${SNS_SUMMARY}}"
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<SERVICE_EVENTS_URL\>/${SERVICE_EVENTS_URL}}"
        SNS_ATTRIBUTES="${SNS_ATTRIBUTES//\<DEPLOYMENT_TASK_LOGS_URL\>/${DEPLOYMENT_TASK_LOGS_URL}}"
        SNS_SENT=$($AWS_CLI sns publish --topic-arn $SNS_TOPIC --subject "$SNS_SUBJECT" --message "$SNS_MESSAGE" --message-attributes "$SNS_ATTRIBUTES" )
    fi

    exit 0
  fi
  
  sleep $every
  i=$(( $i + $every ))
done

# Timeout
failure "New task definition for ${SERVICE} NOT RUNNING within ${ECS_TIMEOUT} seconds" "$DEPLOYMENT_TASK_URL"
exit 1
